#!/usr/bin/env bash
# Generate the Homebrew formula for mobile-cc from a published GitHub Release.
#
# Reads the four per-platform `.sha256` siblings off the release and writes a
# multi-platform prebuilt-binary formula. Run by the release workflow to bump
# the tap (eyalev/homebrew-tap), and runnable by hand to seed/repair it.
#
# Usage:
#   scripts/gen-homebrew-formula.sh <tag> <output-file>
#   e.g. scripts/gen-homebrew-formula.sh v0.5.0 Formula/mobile-cc.rb
#
# Env:
#   MOBILE_CC_REPO   owner/repo to read the release from (default eyalev/mobile-cc)
set -euo pipefail

TAG="${1:?usage: $0 <tag> <output-file>}"
OUT="${2:?usage: $0 <tag> <output-file>}"
REPO="${MOBILE_CC_REPO:-eyalev/mobile-cc}"
VERSION="${TAG#v}"
BASE="https://github.com/${REPO}/releases/download/${TAG}"

T_DARWIN_ARM="aarch64-apple-darwin"
T_DARWIN_INTEL="x86_64-apple-darwin"
T_LINUX_ARM="aarch64-unknown-linux-gnu"
T_LINUX_INTEL="x86_64-unknown-linux-gnu"

sha_for() {
  # Fetch the published .sha256 sibling for a target's version-less tarball.
  local target="$1" sum
  sum=$(curl -fsSL --max-time 60 "${BASE}/mobile-cc-${target}.tar.gz.sha256" | awk '{print $1}')
  if [ -z "$sum" ]; then
    echo "gen-homebrew-formula: could not fetch sha256 for ${target} at ${BASE}" >&2
    exit 1
  fi
  printf '%s' "$sum"
}

SHA_DARWIN_ARM=$(sha_for "$T_DARWIN_ARM")
SHA_DARWIN_INTEL=$(sha_for "$T_DARWIN_INTEL")
SHA_LINUX_ARM=$(sha_for "$T_LINUX_ARM")
SHA_LINUX_INTEL=$(sha_for "$T_LINUX_INTEL")

cat > "$OUT" <<RUBY
# typed: false
# frozen_string_literal: true

# Auto-generated by scripts/gen-homebrew-formula.sh in eyalev/mobile-cc.
# Do not edit by hand — changes are overwritten on the next release.
class MobileCc < Formula
  desc "Drive Claude Code from your phone — mobile-first web UI over tmux"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE}/mobile-cc-${T_DARWIN_ARM}.tar.gz"
      sha256 "${SHA_DARWIN_ARM}"
    end
    on_intel do
      url "${BASE}/mobile-cc-${T_DARWIN_INTEL}.tar.gz"
      sha256 "${SHA_DARWIN_INTEL}"
    end
  end

  on_linux do
    on_arm do
      url "${BASE}/mobile-cc-${T_LINUX_ARM}.tar.gz"
      sha256 "${SHA_LINUX_ARM}"
    end
    on_intel do
      url "${BASE}/mobile-cc-${T_LINUX_INTEL}.tar.gz"
      sha256 "${SHA_LINUX_INTEL}"
    end
  end

  def install
    bin.install "mobile-cc"
  end

  test do
    assert_match "mobile-cc", shell_output("#{bin}/mobile-cc --help")
  end
end
RUBY

echo "wrote $OUT for $TAG"
