#!/usr/bin/env node
// gen-gallery — generate demos/GALLERY.md from demos/manifest.json: ONE
// browsable page with every demo's GIF embedded inline (autoplays in GitHub
// markdown) + links to the sharper MP4 + the recipe. The manifest is the
// single source of truth, so adding a demo there auto-updates the gallery on
// the next capture (run-all.mjs calls this) — the gallery can never drift.
//
//   node demos/gen-gallery.mjs        # regenerate GALLERY.md (CLI)
//   import { generateGallery }        # called from runner/run-all.mjs
//
// DO NOT hand-edit GALLERY.md — your changes are overwritten. Edit this
// generator (or the manifest) instead.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, relative } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url)); // demos/
const ROOT = resolve(HERE, '..'); // repo root
const MEDIA = resolve(ROOT, 'docs', 'media');
const OUT = resolve(HERE, 'GALLERY.md');

// Path relative to GALLERY.md's own location (demos/), POSIX slashes so the
// link resolves on GitHub regardless of the OS that generated it.
const rel = (p) => relative(HERE, p).split('\\').join('/');

export function generateGallery({ quiet = false } = {}) {
  const manifest = JSON.parse(readFileSync(resolve(HERE, 'manifest.json'), 'utf8'));
  const out = [];
  const warnings = [];

  out.push('<!-- GENERATED by demos/gen-gallery.mjs from demos/manifest.json — DO NOT EDIT BY HAND. -->');
  out.push('<!-- Regenerate: `node demos/gen-gallery.mjs` (also runs at the end of every capture). -->');
  out.push('');
  out.push('# Demo gallery');
  out.push('');
  out.push(
    'Every mobile-cc demo, each one a reproducible test (see ' +
      '[`CONVENTIONS.md`](CONVENTIONS.md)). The GIFs below autoplay inline; ' +
      'click any one (or the **MP4** link) for the sharper video, and **recipe** ' +
      'for the capture script.'
  );
  out.push('');

  let count = 0;
  for (const d of manifest.demos) {
    if (!d.media) continue; // test-only demo, nothing to embed
    count++;
    const gif = resolve(MEDIA, `${d.media}.gif`);
    const mp4 = resolve(MEDIA, `${d.media}.mp4`);
    const gifRel = rel(gif);
    const recipe = d.kind === 'terminal' ? `terminal/${d.id}.sh` : `workflows/${d.id}.mjs`;
    // Prefer the minted user-attachments player URL when the manifest has one
    // (plays in-page on GitHub); otherwise a relative link to the committed mp4.
    const mp4Link = d.attachment_url || rel(mp4);
    const kindTag = d.kind === 'terminal' ? ' · `terminal`' : '';

    if (!existsSync(gif)) warnings.push(`${d.id}: gif not found at ${gifRel}`);
    if (!existsSync(mp4) && !d.attachment_url) warnings.push(`${d.id}: mp4 not found at ${rel(mp4)}`);

    out.push(`## ${d.title}`);
    out.push('');
    out.push(d.description);
    out.push('');
    if (existsSync(gif)) {
      // Clickable inline GIF → opens the sharper MP4.
      out.push(`[![${d.title}](${gifRel})](${mp4Link})`);
    } else {
      out.push(`_(GIF not captured yet — run \`demos/local-capture.sh ${d.id}\`.)_`);
    }
    out.push('');
    out.push(`▶ [MP4](${mp4Link}) · [recipe](${recipe})${kindTag}`);
    out.push('');
    out.push('---');
    out.push('');
  }

  out.push(`<sub>${count} demos · generated from \`manifest.json\` by \`gen-gallery.mjs\`.</sub>`);
  out.push('');

  writeFileSync(OUT, out.join('\n'));
  if (!quiet) {
    for (const w of warnings) console.warn(`WARN gen-gallery: ${w}`);
    console.log(`gen-gallery: wrote ${rel(OUT)} — ${count} demos${warnings.length ? `, ${warnings.length} warning(s)` : ''}`);
  }
  return { count, warnings, outPath: OUT };
}

// CLI entry — run directly (not when imported by the runner).
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { warnings } = generateGallery();
  process.exit(warnings.length ? 1 : 0);
}
